name: Deploy and Start React App

on:
  push:
    branches:
      - main # Trigger workflow on push to the main branch

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a compatible Node.js version
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React app
      - name: Build React app
        run: npm run build

      # Step 5: Start the React development server
      - name: Start React App
        run: |
          nohup npm start &
          sleep 10 # Allow the server time to start
          curl -I http://localhost:3000 # Verify the server is running
